:_mod-docs-content-type: PROCEDURE
[id="ols-installing-operator"]
= Installing the OpenShift Lightspeed Operator
:context: ols-installing-operator

.Prerequisites

* You have deployed a cluster on {ocp-product-title} 4.15 or later. The cluster must be connected to the Internet and have telemetry enabled.

* You are logged in to the {ocp-product-title} web console as a user with the cluster-admin role.

* For any command line instructions, it assumes you have already logged into your cluster with the oc CLI.

* You have successfully configured your Large Language Model (LLM) provider so that OpenShift Lightspeed can commnuicate with it.




.Procedure

. In the {ocp-product-title} web console, navigate to the *Operators* -> *OperatorHub* page.

. Search for Lightspeed.

. Locate the Lightspeed Operator, and click to select it.

. When the prompt that discusses the community operator appears, click *Continue*.

. Click *Install*.

. Use the default installation settings presented, and click *Install* to continue.

. Click *Operators* -> *Installed Operators* to verify that the Lightspeed Operator is installed. `Succeeded` should appear in the *Status* column.