// Module included in the following assemblies:
// * lightspeed-docs-main/configure/ols-configuring-openshift-lightspeed.adoc

:_mod-docs-content-type: PROCEDURE
[id="byok-task_{context}"]
= Configuring custom TLS certificates

.Prerequisites

* You are logged in to the {ocp-product-title} web console as a user with the `cluster-admin` role. Alternatively, you are logged in to a user account that has permission to create a cluster-scoped CR file.

* You have configured the large language model (LLM) provider.

* You have installed the {ols-long} Operator.

* You have created the {ols-long} custom resource

.Procedure 

. In the {ocp-product-title} web console, click *Operators* -> *Installed Operators*. 

. Select *All Projects* in the  *Project* dropdown at the top of the screen.

. Click {ols-long} Operator.

. Click *OLSConfig*, then click the `cluster` configuration instance in the list.

. Click the *YAML* tab.

. Modify the `OLSconfig` custom resource to contain the file that contains the TLS secret:
+
.Example `OLSconfig` CR file
[source,yaml,subs="attributes,verbatim"]
----
apiVersion: ols.openshift.io/v1alpha1
kind: OLSConfig
metadata: 
  name: cluster
spec: 
  ols: 
    tlsConfig: 
      keyCertSecretRef: 
        name: lightspeed-tls <1>
---
apiVersion: v1
data: 
  tls.crt: LS0tLS1CRUd...
  tls.key: LS0tLS1CRUd...
kind: Secret
metadata: 
  name: lightspeed-tls
  namespace: openshift-lightspeed
----
<1> Refers to the secret that contains the `tls.crt` and `tls.key` file.

. Click *Save*.