// Module included in the following assemblies:
// release_notes/ols-release-notes.adoc

:_mod-docs-content-type: REFERENCE
[id="ols-0-1-6-release-notes_{context}"]
= {ols-long} version 0.1.7

{ols-official} 0.1.7 is now available on {ocp-product-title} 4.15 and later.

[id="ols-0-1-7-enhancements_{context}"]
== Enhancements

The following enhancements have been made with {ols-official} 0.1.7:

* Beginning in this release, the user interface now uses PatternFly 6 styling and components from the PatternFly Chatbot extension for a more consistent user experience across Red{nbsp}Hat Artificial Intelligence (AI) products.

* With this release, the Red{nbsp}Hat-provided Operator catalogs have moved from OperatorHub to the software catalog and the *Operators* navigation item is renamed to *Ecosystem* in the console. The unified software catalog presents Operators, Helm charts, and other installable content in the same console view.

** To access the Red{nbsp}Hat-provided Operator catalogs in the console, select *Ecosystem* -> *Software Catalog*.
** To manage, update, and remove installed Operators, select *Ecosystem* -> *Installed Operators*.
+
[NOTE]
====
Currently, the console only supports managing Operators by using {olmv0-first}. If you want to use {olmv1} to install and manage cluster extensions, such as Operators, you must use the CLI.
====
+
To manage the default or custom catalog sources, you still interact with OperatorHub custom resource (CR) in the console or CLI.

* With this release, the Service CA Operator automatically adds the {ols-long} default cluster CA certificate to the {ols-long} service trust store. This change simplifies the configuration process for Red Hat OpenShift Application Integration (RHOAI). This enhancement eliminates the need for additional configuration, reducing potential errors due to manual management and ensuring a smoother user experience during deployment.

* With this release, it is now possible to attach `VirtualMachine` details to your prompt from the *VirtualMachine* details page in the Red{nbsp}Hat Advanced Cluster Management for Kubernetes User Interface.

* Beginning in this release, users must now create a `Secret` that contains the header in the `header` path and specify the name of the `Secret` instead of directly specifying header values in the Custom Resource Definition. If you must specify a Kubernetes token, enter the string `kubernetes` instead of the `Secret` name. This is a breaking change that addresses a security breach that occurs if you specify a header value in the CRD `MCPServer.MCPServerStreamableHTTPTransport.Headers` field that is visible in the `OLScConfig` config map.